### PR TITLE
feat: improve the GitHub Actions workflows

### PR DESCRIPTION
**Pull request by Panquesito7**
Things added/changed:

- Improve the GitHub Actions workflows.
  - All new directories do not have to be added manually, those are automatically detected now.
  - Uses new action versions for `setup-r` and `checkout`.
  - Might need testing before merging, though.

### CODE REVIEW

**Review by siriak — DISMISSED** [review]
Looks good, thanks!

**Comment by siriak** [comment]
I can't merge it if MakeDocs is not triggered on its own commits because it's a required PR check

**Comment by siriak** [comment]
image

**Comment by siriak** [comment]
There are 2 issues left unaddressed:
1. MakeDocs is not triggered on its own commits, so I can't merge the PR because of that
2. `unnamed-chunk` file is regenerated every time, could you seed RND in the algorithm that does that?

**Comment by Panquesito7** [comment]
> There are 2 issues left unaddressed:
> 
> 1. MakeDocs is not triggered on its own commits, so I can't merge the PR because of that
> 2. `unnamed-chunk` file is regenerated every time, could you seed RND in the algorithm that does that?

1. Commits by GitHub Actions do not run workflows, that's why that happens (we can evade that, though).
2. Not sure how that is done. Do you have any ideas or? 🤔

**Comment by siriak** [comment]
> Commits by GitHub Actions do not run workflows, that's why that happens (we can evade that, though).

Could you do that? We need to either make them run workflows or make this check optional. Either option works for me.

**Comment by Panquesito7** [comment]
> > Commits by GitHub Actions do not run workflows, that's why that happens (we can evade that, though).
> 
> Could you do that? We need to either make them run workflows or make this check optional. Either option works for me.

Alright, I'll disable the check for now. 🙂
Feel free to approve the PR. Thanks.

**Review by siriak — APPROVED** [review]

**Pull request merged**
