### PR TITLE
Adversarial random forest algorithm for generating synthetic data

### PR DESCRIPTION
**Pull request by Ifeanyi55**
This is an algorithm for generating synthetic data that can be used to train machine learning models.

### CODE REVIEW

**Comment by siriak** [comment]
You are just calling an existing implementation, not implementing it by yourself

**Comment by Ifeanyi55** [comment]
I do not understand what you mean by "calling an existing implementation, not implementing it by yourself." 

I didn't develop the algorithm, quite alright, but I use it, and it works, just as I demonstrated in the R script I shared.

Must every contributed algorithm be originally developed by the contributor? Can you please explain your comment because I saw other contributed algorithms in this repository that are used from existing R packages.

**Comment by siriak** [comment]
Not originally developed, but we try to include implementations of existing algorithms. Like https://github.com/TheAlgorithms/R/blob/master/clustering_algorithms/kmeans_raw_r.r and https://github.com/TheAlgorithms/R/blob/master/searches/binary_search.r. They really provide value because then you can learn how they are implemented. Though it's true that we also have some non-compliant implementations that are just calling library methods.

**Comment by Ifeanyi55** [comment]
Okay, I get it now. Thank you!

**Pull request closed without merging**
