### PR TITLE
linear_search algorithm in R

### PR DESCRIPTION
**Pull request by paras-2407**
I have added a linear search algorithm in R language

### CODE REVIEW

**Comment by paras-2407** [comment]
Please review my changes under label hacktoberfest-accepted and hacktoberfest

**Comment by paras-2407** [comment]
Please review my work and add the label hacktoberfest-accepted and hacktoberfest

**Review by siriak — CHANGES_REQUESTED** [review]
The filename must start with a lowercase letter. Please also put the algorithm in a `searches` folder

**Review by siriak — CHANGES_REQUESTED** [review]
Please also put the algorithm in the `searches` folder

**Comment by siriak** [comment]
This PR has been inactive for a wile, feel free to reopen it when you make the required changes

**Pull request closed without merging**
