### PR TITLE
Create wiggle-sort

### PR DESCRIPTION
**Pull request by iMeet07**
wiggle sort algorithm added

### CODE REVIEW

**Review by siriak — CHANGES_REQUESTED** [review]
`.DS_Store` should not be committed

**Review by siriak — DISMISSED** [review]
Looks good, thanks!

**Comment by iMeet07** [comment]
Thank You So Much. Finally, because if your help I learned it. Thank You so
Much Brother.

**Review by siriak — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
