### PR TITLE
linear_search.r

### PR DESCRIPTION
**Pull request by paras-2407**
I have added linear search program in R as per your requirement in searching_algorithm folder. Now, I request you to please review it and finalise it. I'll be very grateful to contribute to this repository actively if you grant me the label of hacktoberfest and hacktoberfest-accepted labels.

### CODE REVIEW

**Comment by paras-2407** [comment]
Now, please check @siriak

**Review by siriak — APPROVED** [review]
Looks good, thanks!

**Comment by paras-2407** [comment]
As I have contributed in this repository @siriak, please add the label hacktoberfest-accepted to this issue.

**Comment by paras-2407** [comment]
I want to contribute more to this repository under hacktoberfest-accepted label as I saw that there must me more topic in R language which would be benificial.

**Pull request merged**
