### PR TITLE
Implemented Monte Carlo simulation, Markowitz portfolio optimization and Kalman filter

### PR DESCRIPTION
**Pull request by Akshat111111**
1. Monte Carlo simulation is implemented  using the Black-Scholes model.
2. Markowitz portfolio optimization for determining the ideal asset weights in a portfolio with the goal of achieving a desired trade-off between risk and return.
3. Kalman filter in order to  track the price of a financial asset.
Ref-Adding Quantitative finance algorithms #122

### CODE REVIEW

**Review by siriak — COMMENTED** [review]
Could you remove spaces from file paths? That's the way files are usually named here. And maybe move it to `quantitative_finance` directory? I'm waiting for #121 to be merged, and then I'll merge this one.

**Comment by Akshat111111** [comment]
Sure, I will do it

**Comment by Akshat111111** [comment]
Done, please have a look

**Comment by Akshat111111** [comment]
Done.

**Review by siriak — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
