### PR TITLE
searches changed to searching_algorithms

### PR DESCRIPTION
**Pull request by paras-2407**
I have changes searches to searching_algorithms @siriak.

### CODE REVIEW

**Comment by paras-2407** [comment]
Please review it @siriak.

**Comment by paras-2407** [comment]
Now,  I have just one request from you please add hacktoberfest and hacktoberfest-accepted labels to my PR.

**Comment by paras-2407** [comment]
Please review and add the labels hacktoberfest and hacktoberfest-accepted.

**Comment by siriak** [comment]
Why change it? I like the name `searches`

**Pull request closed without merging**
